name: Quality

on:
  pull_request:
    branches:
      - main

jobs:
  generate_matrix:
    name: Get changed packages
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.changed-packages.outputs.packages }}
      empty: ${{ steps.changed-packages.outputs.empty }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find changed packages
        id: changed-packages
        uses: alexshukel/get-changed-workspaces-action@v2.0.0

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build packages
        run: pnpm build

  test:
    name: Test
    needs: [generate_matrix]
    runs-on: ubuntu-latest
    if: ${{ !fromJson(needs.generate_matrix.outputs.empty) }}
    strategy:
      matrix:
        paths: ${{ fromJson(needs.generate_matrix.outputs.packages.paths) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run tests
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: pnpm
          test-script: pnpm test:ci
          skip-step: install
          working-directory: ${{ matrix.paths }}

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run ESLint
        run: pnpm lint

  type:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run typecheck
        run: pnpm typecheck

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run prettier
        run: pnpm format:check
