name: Quality

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build packages
        run: pnpm build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run tests
        run: pnpm test

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run ESLint
        run: pnpm lint

  type:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run typecheck
        run: pnpm typecheck

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run prettier
        run: pnpm format:check

  check-changed-workspaces:
    name: Check changed packages
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.changed-packages.outputs.packages }}
      empty: ${{ steps.changed-packages.outputs.empty }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find changed packages
        id: changed-packages
        uses: AlexShukel/get-changed-workspaces-action@v2.0.0

  coverage:
    name: Coverage
    needs: [check-changed-workspaces]
    runs-on: ubuntu-latest
    if: ${{ !fromJson(needs.check-changed-workspaces.outputs.empty) }}
    strategy:
      matrix:
        package: ${{ fromJson(needs.check-changed-workspaces.outputs.packages) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Check exist tests
        id: tests
        run: |
          if [ -d ${{ matrix.package.path }}/tests ]; then
            echo "name=exist::true" >> $GITHUB_OUTPUT
          else
            echo "name=exist::false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Add PR comment
        if: steps.tests.outputs.exist == 'false'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Coverage report for ${{ matrix.package.name }}
            Test does not exist.

      - name: Get test name
        if: steps.tests.outputs.exist == 'true'
        id: test-name
        run: echo "name=$(echo ${{ matrix.package.path }} | rev | cut -d'/' -f1 | rev)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create coverage report
        if: steps.tests.outputs.exist == 'true'
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: pnpm
          custom-title: Coverage report for ${{ matrix.package.name }}
          test-script: pnpm test:ci ${{ steps.test-name.outputs.name }}
          skip-step: install
