name: Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Sync Files
        uses: Redocly/repo-file-sync-action@master
        with:
          GH_PAT: ${{ secrets.PAT_TOKEN }}
          GIT_EMAIL: hirotomo.yamada@avap.co.jp
          GIT_USERNAME: hirotomoyamada
          COMMIT_PREFIX: ''
